### ISSUE TITLE
Font rendering issues Linux

### ISSUE THREAD

**Issue by tony-aln** [MoonchildProductions/moebius#306]
Basilisk has font rendering problems on Arch Linux. Probably related to #175.
[https://postimg.org/gallery/1jw3pcghc/](https://postimg.org/gallery/1jw3pcghc/)
Firefox ESR 52.5.3 and Pale Moon 27.7.1 screenshots are also in there
Note that when zoomed in, the font rendering appears normal
fontconfig version 2.12.6+5+g665584a
freetype2 version 2.9
harfbuzz version 1.7.4
harfbuzz-icu version 1.7.4
icu version 60.2
Disclaimer: None of the applications were compiled by me, so they're "fresh from the bottle".

**Comment by wolfbeast** [comment]
Please attach the image to the issue. postimg seems to be having problems and using third-party image links always bears the risk of an issue losing its context if the links go dead.

**Comment by wolfbeast** [comment]
#175 was solved.

**Comment by tony-aln** [comment]
Yes, #175 was solved, but on my system because there are still font rendering issues on Basilisk (although not as severe as #175), and only on it. Official build Pale Moon and Firefox ESR built from Mozilla build don't have this issue. Last year, I personally experienced Firefox having font rendering issues, but it was just for a while, and as I use Pale Moon as my main browser, I didn't care much. 
Thank you.

**Comment by wolfbeast** [comment]
Hmm.. looks like font kerning is a bit off when zoomed in. at 1:1 zoom everything seems to be normal.

**Comment by tony-aln** [comment]
I think it's best to compare them full screen on a image viewer, then side by side. On Basilisk, the rendering discrepancies are observed even in the address bar. Note the kerning and tracking between the characters, and the rendering of letters like 'b' 'i' 'l' 'm' 'n' 'p' 'u', it looks like their sides have been "chopped off" 
For instance:
![screenshot_2018-01-19_ comparative](https://user-images.githubusercontent.com/16484161/35201353-7745ce9c-ff12-11e7-950a-dd62e75fa87a.png)

**Comment by zgwerby** [comment]
I've been fixed (so dirty hack or normal decision?) this: only toggled `gfx.*.azure.backends` to cairo instead skia in about:config 

Before:
![2018-02-17 15-42-46](https://user-images.githubusercontent.com/30671470/36341057-463e23d4-13e0-11e8-89b1-0a711ed898b3.png)

After:
![2018-02-17 15-40-12](https://user-images.githubusercontent.com/30671470/36341066-700d35ec-13e0-11e8-8f15-438b0bf91506.png)

Changed settings:
![2018-02-17 15-45-59](https://user-images.githubusercontent.com/30671470/36341080-904a6bcc-13e0-11e8-9813-53398ae308a4.png)

**Comment by wolfbeast** [comment]
The canvas back-end to skia should be fine, that's been the case for a long time already anyway.
As for content... It's been a long time in the making to have skia instead of cairo there; it seems it's still not mature enough. Selecting the default to be cairo's tried-and-tested back-end is probably the better choice (and will also avoid anaemic rendering that it tends to leans towards)

**Comment by tony-aln** [comment]
Yes, @zgwerby, thank you, that solved the problem. @wolfbeast the solution changing the back-end renderer from skia to cairo on those two preferences indeed solves the problem, but I didn't need to change anything on Firefox ESR 52.1 when I first reported the issue.
Inspecting my Firefox backup profiles and the 52.1 profile, I noticed:
v52.1 ESR didn't need the overrides for some reason, neither the updated version (52.6), but Firefox already had gtk3 code for a while.
v56 profile still have the cairo overrides since a long, long while ago. I knew that but I had forgotten, I'd solved the problem own my own last year or the year before.

![screenshot_2018-02-27_15 37 40](https://user-images.githubusercontent.com/16484161/36747788-d87ca6d4-1bed-11e8-9296-c6a75106e1c8.png)

![screenshot_2018-02-27_15 40 08](https://user-images.githubusercontent.com/16484161/36747787-d8482ba2-1bed-11e8-98d1-b74e08b47d56.png)

To effectively solve, then, it's necessary to change the preferences: _gfx.canvas.azure.backends_ and 
_gfx.content.azure.backends_ from _skia_ to _cairo_, maybe even put them as defaults/globals. Shall I close this issue then?

**Comment by wolfbeast** [comment]
As said the canvas back-end set to skia should be fine, since that won't influence font fidelity in content, and is significantly faster for canvas rendering.
Also, if the problem isn't present on ESR-52, then our re-fork (UXP) may also not need this change; it depends on what exactly triggers this, though.

**Comment by tony-aln** [comment]
Well, setting the mentioned prefs back to skia messes up with the font rendering (with the latest prebuilt binaries - 2018.02.14), but not on a new version of Firefox ESR (since 52.2, at least) or the Release channel (I can attest to this since v57, because I'm using a brand new profile for it, with skia enabled by default). 
At some point last year, when Mozilla had the default prefs change from cairo to skia, the same font rendering problems that Basilisk faces today happened, I changed the above preferences to mitigate it. It could have been some code change or even a build config. option modified.
In the archlinux firefox package git repo, there is one change to the build package last year that may have solved the problem: "ac_add_options --with-system-icu" https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/firefox&id=e3529665a1600341545218097b0d0e459ac959b5 which is a setting that persists to this day, which I cannot test, due to limited CPU resources available to build basilisk in a reasonable amount of time.
About GTK, I agreed and agree with you, I'm truly sorry for apparently expressing my ideas poorly.

**Comment by wolfbeast** [comment]
ICU has nothing to do with font rendering, so that's certainly not it.
